#!/usr/bin/env python3
"""
Simple CGI script for testing
"""

import os
import sys
import cgi
import cgitb
from datetime import datetime

# Enable CGI error reporting
cgitb.enable()

def main():
    # Print HTTP headers
    print("Content-Type: text/html; charset=utf-8")
    print()  # Empty line to end headers
    
    # Print HTML content
    print("""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CGI Test Script</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }
        .container {
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        h1 {
            color: #333;
            text-align: center;
        }
        .info-section {
            margin: 20px 0;
            padding: 15px;
            background: #f8f9fa;
            border-left: 4px solid #007bff;
        }
        .env-var {
            font-family: monospace;
            background: #e9ecef;
            padding: 2px 4px;
            border-radius: 3px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 10px 0;
        }
        th, td {
            text-align: left;
            padding: 8px;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f8f9fa;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🐍 CGI Test Script</h1>
        <p>This page is generated by a Python CGI script running on the Localhost HTTP Server!</p>
        
        <div class="info-section">
            <h3>📊 Request Information</h3>
            <table>
                <tr><th>Property</th><th>Value</th></tr>""")
    
    # Display request information
    request_info = [
        ("Request Method", os.environ.get('REQUEST_METHOD', 'Unknown')),
        ("Request URI", os.environ.get('REQUEST_URI', 'Unknown')),
        ("Query String", os.environ.get('QUERY_STRING', 'None')),
        ("Content Type", os.environ.get('CONTENT_TYPE', 'None')),
        ("Content Length", os.environ.get('CONTENT_LENGTH', 'None')),
        ("Server Name", os.environ.get('SERVER_NAME', 'Unknown')),
        ("Server Port", os.environ.get('SERVER_PORT', 'Unknown')),
        ("Remote Address", os.environ.get('REMOTE_ADDR', 'Unknown')),
        ("User Agent", os.environ.get('HTTP_USER_AGENT', 'Unknown')),
    ]
    
    for name, value in request_info:
        print(f"                <tr><td>{name}</td><td class='env-var'>{value}</td></tr>")
    
    print("""            </table>
        </div>
        
        <div class="info-section">
            <h3>🕒 Server Information</h3>
            <p><strong>Current Time:</strong> {}</p>
            <p><strong>Python Version:</strong> {}</p>
            <p><strong>Script Path:</strong> <span class="env-var">{}</span></p>
            <p><strong>Gateway Interface:</strong> <span class="env-var">{}</span></p>
        </div>""".format(
        datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        sys.version,
        os.environ.get('SCRIPT_NAME', 'Unknown'),
        os.environ.get('GATEWAY_INTERFACE', 'Unknown')
    ))
    
    # Handle POST data if present
    if os.environ.get('REQUEST_METHOD') == 'POST':
        print("""
        <div class="info-section">
            <h3>📝 POST Data</h3>""")
        
        try:
            form = cgi.FieldStorage()
            if form:
                print("            <table>")
                print("                <tr><th>Field Name</th><th>Value</th></tr>")
                for field in form.keys():
                    value = form.getvalue(field)
                    print(f"                <tr><td>{field}</td><td class='env-var'>{value}</td></tr>")
                print("            </table>")
            else:
                print("            <p>No POST data received.</p>")
        except Exception as e:
            print(f"            <p>Error parsing POST data: {e}</p>")
        
        print("        </div>")
    
    # Display some environment variables
    print("""
        <div class="info-section">
            <h3>🌍 Environment Variables</h3>
            <table>
                <tr><th>Variable</th><th>Value</th></tr>""")
    
    env_vars = ['GATEWAY_INTERFACE', 'SERVER_SOFTWARE', 'SERVER_PROTOCOL', 
                'REQUEST_METHOD', 'PATH_INFO', 'QUERY_STRING', 'CONTENT_TYPE', 
                'CONTENT_LENGTH', 'HTTP_HOST', 'HTTP_ACCEPT']
    
    for var in env_vars:
        value = os.environ.get(var, 'Not set')
        print(f"                <tr><td>{var}</td><td class='env-var'>{value}</td></tr>")
    
    print("""            </table>
        </div>
        
        <div class="info-section">
            <h3>✅ CGI Test Results</h3>
            <p>✓ CGI script executed successfully</p>
            <p>✓ Environment variables are properly set</p>
            <p>✓ HTTP headers are correctly formatted</p>
            <p>✓ Python CGI integration is working</p>
        </div>
        
        <p style="text-align: center; margin-top: 30px;">
            <a href="/">← Return to Home</a>
        </p>
    </div>
</body>
</html>""")

if __name__ == "__main__":
    main()
